name: cool_date_night
description: A  Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluro: ^1.5.0
  cloud_firestore: ^0.12.7
  auto_size_text: ^2.0.1
  firebase_auth: ^0.11.1+10
  rxdart: ^0.22.0
  flutter_screenutil: ^0.5.3
  image_picker: ^0.6.0+3
  firebase_storage: ^3.0.3
  permission_handler: ^3.2.1+1
  cached_network_image: ^1.1.1
  photo_view: ^0.3.1
  url_launcher: ^5.1.2
  font_awesome_flutter: ^8.5.0
  flutter_inapp_purchase: ^2.0.4
  oauth2: ^1.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/launcher_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/free.png
    - assets/img/icebreaker.png
    - assets/img/gear.png
    - assets/img/parents'.png
    - assets/img/spicy.png
    - assets/img/trivia.png
    - assets/img/vitalizer.png
    - assets/img/lauren.png
    - assets/img/darkblue.jpg
    - assets/img/bluebackground.png
    - assets/img/bluegradient.png
    - assets/img/broken-heart.png
    - assets/img/camera.png
    - assets/img/magnifier-with-a-heart.png
    - assets/img/launcher_icon.png
    - assets/img/cooldatenightmustard.png
  fonts:
    - family: DKVisum
      fonts:
        - asset: assets/fonts/DK_Visum.ttf
    - family: Optima
      fonts:
        - asset: assets/fonts/Optima_Medium.ttf
          weight: 400
        - asset: assets/fonts/Optima_Bold.ttf
          weight: 700
        - asset: assets/fonts/Optima_Normal.TTF
          weight: 300
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
